baseurl: https://Rchaeopteryx.netlify.app/
languageCode: en-us
theme: hugo-theme-terminal
paginate: 5
params:
  centerTheme: yes
  contentTypeName: post
  fullWidthTheme: no
  showMenuItems: 5
  themeColor: orange
languages:
  en:
    copyright: ''
    keywords: ''
    menu:
      main:
        - identifier: about
          name: Ãœber mich
          url: /ich
        - identifier: showcase
          name: QGIS
          url: /QGIS
    menuMore: mehr
    params:
      logo:
        logoHomeLink: /
        logoText: Rchaeopteryx
    readMore: weiterlesen
    readOtherPosts: weitere Artikel
    subtitle: Meine R-Projekte
    title: Rchaeopteryx
